#include "aicpp/DslSystem.h"
#include "aicpp/Hodel.h"

using namespace aicpp;

std::map<std::string, Neuron> aicpp::dslVariableNeurons()
{
    std::map<std::string, Neuron> neurons;

    neurons.emplace("F", Neuron{"F", [] (std::vector<std::any> const&) -> std::any { return hodel::F; }, std::vector<std::type_index>{}, typeid(hodel::Boolean)});
    neurons.emplace("T", Neuron{"T", [] (std::vector<std::any> const&) -> std::any { return hodel::T; }, std::vector<std::type_index>{}, typeid(hodel::Boolean)});
    neurons.emplace("ZERO", Neuron{"ZERO", [] (std::vector<std::any> const&) -> std::any { return hodel::ZERO; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("ONE", Neuron{"ONE", [] (std::vector<std::any> const&) -> std::any { return hodel::ONE; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("TWO", Neuron{"TWO", [] (std::vector<std::any> const&) -> std::any { return hodel::TWO; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("THREE", Neuron{"THREE", [] (std::vector<std::any> const&) -> std::any { return hodel::THREE; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("FOUR", Neuron{"FOUR", [] (std::vector<std::any> const&) -> std::any { return hodel::FOUR; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("FIVE", Neuron{"FIVE", [] (std::vector<std::any> const&) -> std::any { return hodel::FIVE; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("SIX", Neuron{"SIX", [] (std::vector<std::any> const&) -> std::any { return hodel::SIX; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("SEVEN", Neuron{"SEVEN", [] (std::vector<std::any> const&) -> std::any { return hodel::SEVEN; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("EIGHT", Neuron{"EIGHT", [] (std::vector<std::any> const&) -> std::any { return hodel::EIGHT; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("NINE", Neuron{"NINE", [] (std::vector<std::any> const&) -> std::any { return hodel::NINE; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("TEN", Neuron{"TEN", [] (std::vector<std::any> const&) -> std::any { return hodel::TEN; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("NEG_ONE", Neuron{"NEG_ONE", [] (std::vector<std::any> const&) -> std::any { return hodel::NEG_ONE; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});
    neurons.emplace("NEG_TWO", Neuron{"NEG_TWO", [] (std::vector<std::any> const&) -> std::any { return hodel::NEG_TWO; }, std::vector<std::type_index>{}, typeid(hodel::Integer)});

    neurons.emplace("identity", Neuron{"identity", hodel::identity, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("add", Neuron{"add", hodel::add, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("subtract", Neuron{"subtract", hodel::subtract, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("multiply", Neuron{"multiply", hodel::multiply, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("divide", Neuron{"divide", hodel::divide, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("invert", Neuron{"invert", hodel::invert, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("even", Neuron{"even", hodel::even, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("double", Neuron{"double", hodel::double_, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("halve", Neuron{"halve", hodel::halve, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("flip", Neuron{"flip", hodel::flip, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("equality", Neuron{"equality", hodel::equality, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("contained", Neuron{"contained", hodel::contained, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("combine", Neuron{"combine", hodel::combine, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("intersection", Neuron{"intersection", hodel::intersection, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("difference", Neuron{"difference", hodel::difference, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("dedupe", Neuron{"dedupe", hodel::dedupe, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("order", Neuron{"order", hodel::order, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("repeat", Neuron{"repeat", hodel::repeat, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("greater", Neuron{"greater", hodel::greater, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("size", Neuron{"size", hodel::size, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("maximum", Neuron{"maximum", hodel::maximum, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("minimum", Neuron{"minimum", hodel::minimum, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("valmax", Neuron{"valmax", hodel::valmax, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("valmin", Neuron{"valmin", hodel::valmin, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("initset", Neuron{"initset", hodel::initset, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("both", Neuron{"both", hodel::both, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("either", Neuron{"either", hodel::either, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("increment", Neuron{"increment", hodel::increment, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("decrement", Neuron{"decrement", hodel::decrement, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("crement", Neuron{"crement", hodel::crement, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("sign", Neuron{"sign", hodel::sign, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("positive", Neuron{"positive", hodel::positive, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("toivec", Neuron{"toivec", hodel::toivec, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("tojvec", Neuron{"tojvec", hodel::tojvec, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("totuple", Neuron{"totuple", hodel::totuple, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("first", Neuron{"first", hodel::first, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("last", Neuron{"last", hodel::last, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("interval", Neuron{"interval", hodel::interval, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("astuple", Neuron{"astuple", hodel::astuple, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("branch", Neuron{"branch", hodel::branch, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("compose", Neuron{"compose", hodel::compose, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("chain", Neuron{"chain", hodel::chain, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("matcher", Neuron{"matcher", hodel::matcher, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("rbind", Neuron{"rbind", hodel::rbind, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("lbind", Neuron{"lbind", hodel::lbind, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("fork", Neuron{"fork", hodel::fork, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("height", Neuron{"height", hodel::height, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("width", Neuron{"width", hodel::width, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("shape", Neuron{"shape", hodel::shape, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("portrait", Neuron{"portrait", hodel::portrait, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("asindices", Neuron{"asindices", hodel::asindices, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("ofcolor", Neuron{"ofcolor", hodel::ofcolor, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("ulcorner", Neuron{"ulcorner", hodel::ulcorner, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("urcorner", Neuron{"urcorner", hodel::urcorner, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("llcorner", Neuron{"llcorner", hodel::llcorner, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("lrcorner", Neuron{"lrcorner", hodel::lrcorner, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("crop", Neuron{"crop", hodel::crop, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("toindices", Neuron{"toindices", hodel::toindices, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("shift", Neuron{"shift", hodel::shift, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("uppermost", Neuron{"uppermost", hodel::uppermost, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("lowermost", Neuron{"lowermost", hodel::lowermost, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("leftmost", Neuron{"leftmost", hodel::leftmost, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("rightmost", Neuron{"rightmost", hodel::rightmost, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("bordering", Neuron{"bordering", hodel::bordering, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("rot90", Neuron{"rot90", hodel::rot90, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("rot180", Neuron{"rot180", hodel::rot180, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("rot270", Neuron{"rot270", hodel::rot270, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("hmirror", Neuron{"hmirror", hodel::hmirror, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("vmirror", Neuron{"vmirror", hodel::vmirror, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("dmirror", Neuron{"dmirror", hodel::dmirror, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("cmirror", Neuron{"cmirror", hodel::cmirror, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("hupscale", Neuron{"hupscale", hodel::hupscale, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("vupscale", Neuron{"vupscale", hodel::vupscale, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("upscale", Neuron{"upscale", hodel::upscale, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("downscale", Neuron{"downscale", hodel::downscale, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("hconcat", Neuron{"hconcat", hodel::hconcat, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("vconcat", Neuron{"vconcat", hodel::vconcat, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("subgrid", Neuron{"subgrid", hodel::subgrid, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("cellwise", Neuron{"cellwise", hodel::cellwise, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("replace", Neuron{"replace", hodel::replace, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("switch", Neuron{"switch", hodel::switch_, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("center", Neuron{"center", hodel::center, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("position", Neuron{"position", hodel::position, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("index", Neuron{"index", hodel::index, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("canvas", Neuron{"canvas", hodel::canvas, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("corners", Neuron{"corners", hodel::corners, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("trim", Neuron{"trim", hodel::trim, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("tophalf", Neuron{"tophalf", hodel::tophalf, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("bottomhalf", Neuron{"bottomhalf", hodel::bottomhalf, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("lefthalf", Neuron{"lefthalf", hodel::lefthalf, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});
    neurons.emplace("righthalf", Neuron{"righthalf", hodel::righthalf, std::vector<std::type_index>{}, typeid(std::function<std::any(std::vector<std::any> const&)>)});

    return neurons;
}

std::map<std::string, Neuron> aicpp::dslPrimitiveNeurons()
{
    std::map<std::string, Neuron> neurons;

    neurons.emplace("identity0", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::Boolean)}, typeid(hodel::Boolean)});
    neurons.emplace("identity1", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::Cell)}, typeid(hodel::Cell)});
    neurons.emplace("identity2", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("identity3", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("identity4", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("identity5", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("identity6", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("identity7", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("identity8", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Object)});
    neurons.emplace("identity9", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Objects)});
    neurons.emplace("identity10", Neuron{"identity", hodel::identity, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Patch)});
    neurons.emplace("add0", Neuron{"add", hodel::add, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("add1", Neuron{"add", hodel::add, std::vector<std::type_index>{typeid(hodel::IntegerTuple), typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("subtract0", Neuron{"subtract", hodel::subtract, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("subtract1", Neuron{"subtract", hodel::subtract, std::vector<std::type_index>{typeid(hodel::IntegerTuple), typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("multiply0", Neuron{"multiply", hodel::multiply, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("multiply1", Neuron{"multiply", hodel::multiply, std::vector<std::type_index>{typeid(hodel::IntegerTuple), typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("divide0", Neuron{"divide", hodel::divide, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("divide1", Neuron{"divide", hodel::divide, std::vector<std::type_index>{typeid(hodel::IntegerTuple), typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("invert0", Neuron{"invert", hodel::invert, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("invert1", Neuron{"invert", hodel::invert, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("even", Neuron{"even", hodel::even, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Boolean)});
    neurons.emplace("double0", Neuron{"double", hodel::double_, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("double1", Neuron{"double", hodel::double_, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("halve0", Neuron{"halve", hodel::halve, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("halve1", Neuron{"halve", hodel::halve, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("flip", Neuron{"flip", hodel::flip, std::vector<std::type_index>{typeid(hodel::Boolean)}, typeid(hodel::Boolean)});
    neurons.emplace("equality0", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::Boolean)}, typeid(hodel::Boolean)});
    neurons.emplace("equality1", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::Cell)}, typeid(hodel::Cell)});
    neurons.emplace("equality2", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("equality3", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("equality4", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("equality5", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("equality6", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("equality7", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("equality8", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Object)});
    neurons.emplace("equality9", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Objects)});
    neurons.emplace("equality10", Neuron{"equality", hodel::equality, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Patch)});
    neurons.emplace("contained0", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained1", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained2", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained3", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained4", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained5", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("contained6", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Cell), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained7", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Cell), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained8", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Cell), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained9", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Cell), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained10", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Cell), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained11", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Cell), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("contained12", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained13", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained14", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained15", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained16", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained17", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("contained18", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained19", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained20", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained21", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained22", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained23", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("contained24", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IndicesSet), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained25", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IndicesSet), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained26", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IndicesSet), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained27", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IndicesSet), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained28", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IndicesSet), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained29", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IndicesSet), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("contained30", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained31", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained32", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained33", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained34", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained35", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("contained36", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerSet), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained37", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerSet), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained38", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerSet), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained39", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerSet), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained40", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerSet), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained41", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerSet), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("contained42", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerTuple), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained43", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerTuple), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained44", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerTuple), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained45", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerTuple), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained46", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerTuple), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained47", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::IntegerTuple), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("contained48", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained49", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained50", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained51", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained52", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained53", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("contained54", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Objects), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained55", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Objects), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained56", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Objects), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained57", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Objects), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained58", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Objects), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained59", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Objects), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("contained60", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Patch), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("contained61", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Patch), typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("contained62", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Patch), typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained63", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Patch), typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("contained64", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Patch), typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("contained65", Neuron{"contained", hodel::contained, std::vector<std::type_index>{typeid(hodel::Patch), typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("combine0", Neuron{"combine", hodel::combine, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("combine1", Neuron{"combine", hodel::combine, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("combine2", Neuron{"combine", hodel::combine, std::vector<std::type_index>{typeid(hodel::IndicesSet), typeid(hodel::IndicesSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("combine3", Neuron{"combine", hodel::combine, std::vector<std::type_index>{typeid(hodel::IntegerSet), typeid(hodel::IntegerSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("combine4", Neuron{"combine", hodel::combine, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Object)}, typeid(hodel::Object)});
    neurons.emplace("combine5", Neuron{"combine", hodel::combine, std::vector<std::type_index>{typeid(hodel::Objects), typeid(hodel::Objects)}, typeid(hodel::Objects)});
    neurons.emplace("intersection0", Neuron{"intersection", hodel::intersection, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("intersection1", Neuron{"intersection", hodel::intersection, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("intersection2", Neuron{"intersection", hodel::intersection, std::vector<std::type_index>{typeid(hodel::IndicesSet), typeid(hodel::IndicesSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("intersection3", Neuron{"intersection", hodel::intersection, std::vector<std::type_index>{typeid(hodel::IntegerSet), typeid(hodel::IntegerSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("intersection4", Neuron{"intersection", hodel::intersection, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Object)}, typeid(hodel::Object)});
    neurons.emplace("intersection5", Neuron{"intersection", hodel::intersection, std::vector<std::type_index>{typeid(hodel::Objects), typeid(hodel::Objects)}, typeid(hodel::Objects)});
    neurons.emplace("difference0", Neuron{"difference", hodel::difference, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("difference1", Neuron{"difference", hodel::difference, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("difference2", Neuron{"difference", hodel::difference, std::vector<std::type_index>{typeid(hodel::IndicesSet), typeid(hodel::IndicesSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("difference3", Neuron{"difference", hodel::difference, std::vector<std::type_index>{typeid(hodel::IntegerSet), typeid(hodel::IntegerSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("difference4", Neuron{"difference", hodel::difference, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Object)}, typeid(hodel::Object)});
    neurons.emplace("difference5", Neuron{"difference", hodel::difference, std::vector<std::type_index>{typeid(hodel::Objects), typeid(hodel::Objects)}, typeid(hodel::Objects)});
    neurons.emplace("greater", Neuron{"greater", hodel::greater, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::Integer)}, typeid(hodel::Boolean)});
    neurons.emplace("size0", Neuron{"size", hodel::size, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Integer)});
    neurons.emplace("size1", Neuron{"size", hodel::size, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Integer)});
    neurons.emplace("size2", Neuron{"size", hodel::size, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Integer)});
    neurons.emplace("size3", Neuron{"size", hodel::size, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Integer)});
    neurons.emplace("size4", Neuron{"size", hodel::size, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Integer)});
    neurons.emplace("size5", Neuron{"size", hodel::size, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Integer)});
    neurons.emplace("maximum", Neuron{"maximum", hodel::maximum, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Integer)});
    neurons.emplace("minimum", Neuron{"minimum", hodel::minimum, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Integer)});
    neurons.emplace("initset0", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Boolean)}, typeid(hodel::Grid)});
    neurons.emplace("initset1", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Cell)}, typeid(hodel::Grid)});
    neurons.emplace("initset2", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("initset3", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Grid)});
    neurons.emplace("initset4", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Grid)});
    neurons.emplace("initset5", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Grid)});
    neurons.emplace("initset6", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Grid)});
    neurons.emplace("initset7", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::Grid)});
    neurons.emplace("initset8", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Grid)});
    neurons.emplace("initset9", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Grid)});
    neurons.emplace("initset10", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Grid)});
    neurons.emplace("initset12", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Boolean)}, typeid(hodel::Indices)});
    neurons.emplace("initset13", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Cell)}, typeid(hodel::Indices)});
    neurons.emplace("initset14", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Indices)});
    neurons.emplace("initset15", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("initset16", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Indices)});
    neurons.emplace("initset17", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Indices)});
    neurons.emplace("initset18", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Indices)});
    neurons.emplace("initset19", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::Indices)});
    neurons.emplace("initset20", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Indices)});
    neurons.emplace("initset21", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Indices)});
    neurons.emplace("initset22", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Indices)});
    neurons.emplace("initset24", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Boolean)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset25", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Cell)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset26", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset27", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset28", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset29", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset30", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset31", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset32", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset33", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset34", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::IndicesSet)});
    neurons.emplace("initset36", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Boolean)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset37", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Cell)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset38", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset39", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset40", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset41", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset42", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset43", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset44", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset45", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset46", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::IntegerSet)});
    neurons.emplace("initset48", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Boolean)}, typeid(hodel::Object)});
    neurons.emplace("initset49", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Cell)}, typeid(hodel::Object)});
    neurons.emplace("initset50", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Object)});
    neurons.emplace("initset51", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Object)});
    neurons.emplace("initset52", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Object)});
    neurons.emplace("initset53", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Object)});
    neurons.emplace("initset54", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Object)});
    neurons.emplace("initset55", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::Object)});
    neurons.emplace("initset56", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Object)});
    neurons.emplace("initset57", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Object)});
    neurons.emplace("initset58", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Object)});
    neurons.emplace("initset60", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Boolean)}, typeid(hodel::Objects)});
    neurons.emplace("initset61", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Cell)}, typeid(hodel::Objects)});
    neurons.emplace("initset62", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Objects)});
    neurons.emplace("initset63", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Objects)});
    neurons.emplace("initset64", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Objects)});
    neurons.emplace("initset65", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Objects)});
    neurons.emplace("initset66", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Objects)});
    neurons.emplace("initset67", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::Objects)});
    neurons.emplace("initset68", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Objects)});
    neurons.emplace("initset69", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Objects)});
    neurons.emplace("initset70", Neuron{"initset", hodel::initset, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Objects)});
    neurons.emplace("both", Neuron{"both", hodel::both, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Boolean)}, typeid(hodel::Boolean)});
    neurons.emplace("either", Neuron{"either", hodel::either, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Boolean)}, typeid(hodel::Boolean)});
    neurons.emplace("increment0", Neuron{"increment", hodel::increment, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("increment1", Neuron{"increment", hodel::increment, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("decrement0", Neuron{"decrement", hodel::decrement, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("decrement1", Neuron{"decrement", hodel::decrement, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("crement0", Neuron{"crement", hodel::crement, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("crement1", Neuron{"crement", hodel::crement, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("sign0", Neuron{"sign", hodel::sign, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("sign1", Neuron{"sign", hodel::sign, std::vector<std::type_index>{typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("positive", Neuron{"positive", hodel::positive, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::Boolean)});
    neurons.emplace("toivec", Neuron{"toivec", hodel::toivec, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("tojvec", Neuron{"tojvec", hodel::tojvec, std::vector<std::type_index>{typeid(hodel::Integer)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("first0", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("first1", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("first2", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("first3", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("first4", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("first5", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("first6", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Cell)});
    neurons.emplace("first7", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Cell)});
    neurons.emplace("first8", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Cell)});
    neurons.emplace("first9", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Cell)});
    neurons.emplace("first10", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Cell)});
    neurons.emplace("first11", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Cell)});
    neurons.emplace("first12", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("first13", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Grid)});
    neurons.emplace("first14", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Grid)});
    neurons.emplace("first15", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Grid)});
    neurons.emplace("first16", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Grid)});
    neurons.emplace("first17", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Grid)});
    neurons.emplace("first18", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Indices)});
    neurons.emplace("first19", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("first20", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Indices)});
    neurons.emplace("first21", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Indices)});
    neurons.emplace("first22", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Indices)});
    neurons.emplace("first23", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Indices)});
    neurons.emplace("first24", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::IndicesSet)});
    neurons.emplace("first25", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::IndicesSet)});
    neurons.emplace("first26", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("first27", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("first28", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::IndicesSet)});
    neurons.emplace("first29", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::IndicesSet)});
    neurons.emplace("first30", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Integer)});
    neurons.emplace("first31", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Integer)});
    neurons.emplace("first32", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Integer)});
    neurons.emplace("first33", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Integer)});
    neurons.emplace("first34", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Integer)});
    neurons.emplace("first35", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Integer)});
    neurons.emplace("first36", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::IntegerSet)});
    neurons.emplace("first37", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::IntegerSet)});
    neurons.emplace("first38", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("first39", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("first40", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::IntegerSet)});
    neurons.emplace("first41", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::IntegerSet)});
    neurons.emplace("first42", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("first43", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("first44", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("first45", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("first46", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("first47", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("first48", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Object)});
    neurons.emplace("first49", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Object)});
    neurons.emplace("first50", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Object)});
    neurons.emplace("first51", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Object)});
    neurons.emplace("first52", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Object)});
    neurons.emplace("first53", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Object)});
    neurons.emplace("first54", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Objects)});
    neurons.emplace("first55", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Objects)});
    neurons.emplace("first56", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Objects)});
    neurons.emplace("first57", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Objects)});
    neurons.emplace("first58", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Objects)});
    neurons.emplace("first59", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Objects)});
    neurons.emplace("first60", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Patch)});
    neurons.emplace("first61", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Patch)});
    neurons.emplace("first62", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Patch)});
    neurons.emplace("first63", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Patch)});
    neurons.emplace("first64", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Patch)});
    neurons.emplace("first65", Neuron{"first", hodel::first, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Patch)});
    neurons.emplace("last0", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("last1", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Boolean)});
    neurons.emplace("last2", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Boolean)});
    neurons.emplace("last3", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Boolean)});
    neurons.emplace("last4", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Boolean)});
    neurons.emplace("last5", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Boolean)});
    neurons.emplace("last6", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Cell)});
    neurons.emplace("last7", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Cell)});
    neurons.emplace("last8", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Cell)});
    neurons.emplace("last9", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Cell)});
    neurons.emplace("last10", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Cell)});
    neurons.emplace("last11", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Cell)});
    neurons.emplace("last12", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("last13", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Grid)});
    neurons.emplace("last14", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Grid)});
    neurons.emplace("last15", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Grid)});
    neurons.emplace("last16", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Grid)});
    neurons.emplace("last17", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Grid)});
    neurons.emplace("last18", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Indices)});
    neurons.emplace("last19", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("last20", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Indices)});
    neurons.emplace("last21", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Indices)});
    neurons.emplace("last22", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Indices)});
    neurons.emplace("last23", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Indices)});
    neurons.emplace("last24", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::IndicesSet)});
    neurons.emplace("last25", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::IndicesSet)});
    neurons.emplace("last26", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("last27", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("last28", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::IndicesSet)});
    neurons.emplace("last29", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::IndicesSet)});
    neurons.emplace("last30", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Integer)});
    neurons.emplace("last31", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Integer)});
    neurons.emplace("last32", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Integer)});
    neurons.emplace("last33", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Integer)});
    neurons.emplace("last34", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Integer)});
    neurons.emplace("last35", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Integer)});
    neurons.emplace("last36", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::IntegerSet)});
    neurons.emplace("last37", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::IntegerSet)});
    neurons.emplace("last38", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("last39", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("last40", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::IntegerSet)});
    neurons.emplace("last41", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::IntegerSet)});
    neurons.emplace("last42", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("last43", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("last44", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("last45", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("last46", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("last47", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("last48", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Object)});
    neurons.emplace("last49", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Object)});
    neurons.emplace("last50", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Object)});
    neurons.emplace("last51", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Object)});
    neurons.emplace("last52", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Object)});
    neurons.emplace("last53", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Object)});
    neurons.emplace("last54", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Objects)});
    neurons.emplace("last55", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Objects)});
    neurons.emplace("last56", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Objects)});
    neurons.emplace("last57", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Objects)});
    neurons.emplace("last58", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Objects)});
    neurons.emplace("last59", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Objects)});
    neurons.emplace("last60", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Patch)});
    neurons.emplace("last61", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Patch)});
    neurons.emplace("last62", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IndicesSet)}, typeid(hodel::Patch)});
    neurons.emplace("last63", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::IntegerSet)}, typeid(hodel::Patch)});
    neurons.emplace("last64", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Patch)});
    neurons.emplace("last65", Neuron{"last", hodel::last, std::vector<std::type_index>{typeid(hodel::Objects)}, typeid(hodel::Patch)});
    neurons.emplace("astuple", Neuron{"astuple", hodel::astuple, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::Integer)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("branch0", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Boolean), typeid(hodel::Boolean)}, typeid(hodel::Boolean)});
    neurons.emplace("branch1", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Cell), typeid(hodel::Cell)}, typeid(hodel::Cell)});
    neurons.emplace("branch2", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Grid), typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("branch3", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Indices), typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("branch4", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::IndicesSet), typeid(hodel::IndicesSet)}, typeid(hodel::IndicesSet)});
    neurons.emplace("branch5", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Integer), typeid(hodel::Integer)}, typeid(hodel::Integer)});
    neurons.emplace("branch6", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::IntegerSet), typeid(hodel::IntegerSet)}, typeid(hodel::IntegerSet)});
    neurons.emplace("branch7", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::IntegerTuple), typeid(hodel::IntegerTuple)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("branch8", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Object), typeid(hodel::Object)}, typeid(hodel::Object)});
    neurons.emplace("branch9", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Objects), typeid(hodel::Objects)}, typeid(hodel::Objects)});
    neurons.emplace("branch10", Neuron{"branch", hodel::branch, std::vector<std::type_index>{typeid(hodel::Boolean), typeid(hodel::Patch), typeid(hodel::Patch)}, typeid(hodel::Patch)});
    neurons.emplace("height0", Neuron{"height", hodel::height, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Integer)});
    neurons.emplace("height1", Neuron{"height", hodel::height, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Integer)});
    neurons.emplace("width0", Neuron{"width", hodel::width, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Integer)});
    neurons.emplace("width1", Neuron{"width", hodel::width, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Integer)});
    neurons.emplace("shape0", Neuron{"shape", hodel::shape, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("shape1", Neuron{"shape", hodel::shape, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("portrait0", Neuron{"portrait", hodel::portrait, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("portrait1", Neuron{"portrait", hodel::portrait, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Boolean)});
    neurons.emplace("asindices", Neuron{"asindices", hodel::asindices, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Indices)});
    neurons.emplace("ofcolor", Neuron{"ofcolor", hodel::ofcolor, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Integer)}, typeid(hodel::Indices)});
    neurons.emplace("crop", Neuron{"crop", hodel::crop, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::IntegerTuple), typeid(hodel::IntegerTuple)}, typeid(hodel::Grid)});
    neurons.emplace("toindices0", Neuron{"toindices", hodel::toindices, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("toindices1", Neuron{"toindices", hodel::toindices, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Indices)});
    neurons.emplace("shift0", Neuron{"shift", hodel::shift, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::IntegerTuple)}, typeid(hodel::Indices)});
    neurons.emplace("shift1", Neuron{"shift", hodel::shift, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::IntegerTuple)}, typeid(hodel::Object)});
    neurons.emplace("uppermost0", Neuron{"uppermost", hodel::uppermost, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Integer)});
    neurons.emplace("uppermost1", Neuron{"uppermost", hodel::uppermost, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Integer)});
    neurons.emplace("lowermost0", Neuron{"lowermost", hodel::lowermost, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Integer)});
    neurons.emplace("lowermost1", Neuron{"lowermost", hodel::lowermost, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Integer)});
    neurons.emplace("leftmost0", Neuron{"leftmost", hodel::leftmost, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Integer)});
    neurons.emplace("leftmost1", Neuron{"leftmost", hodel::leftmost, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Integer)});
    neurons.emplace("rightmost0", Neuron{"rightmost", hodel::rightmost, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Integer)});
    neurons.emplace("rightmost1", Neuron{"rightmost", hodel::rightmost, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Integer)});
    neurons.emplace("bordering0", Neuron{"bordering", hodel::bordering, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("bordering1", Neuron{"bordering", hodel::bordering, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Grid)}, typeid(hodel::Boolean)});
    neurons.emplace("rot90", Neuron{"rot90", hodel::rot90, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("rot180", Neuron{"rot180", hodel::rot180, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("rot270", Neuron{"rot270", hodel::rot270, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("hmirror0", Neuron{"hmirror", hodel::hmirror, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("hmirror1", Neuron{"hmirror", hodel::hmirror, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Patch)});
    neurons.emplace("vmirror0", Neuron{"vmirror", hodel::vmirror, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("vmirror1", Neuron{"vmirror", hodel::vmirror, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Patch)});
    neurons.emplace("dmirror0", Neuron{"dmirror", hodel::dmirror, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("dmirror1", Neuron{"dmirror", hodel::dmirror, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Patch)});
    neurons.emplace("cmirror0", Neuron{"cmirror", hodel::cmirror, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("cmirror1", Neuron{"cmirror", hodel::cmirror, std::vector<std::type_index>{typeid(hodel::Patch)}, typeid(hodel::Patch)});
    neurons.emplace("hupscale", Neuron{"hupscale", hodel::hupscale, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Integer)}, typeid(hodel::Grid)});
    neurons.emplace("vupscale", Neuron{"vupscale", hodel::vupscale, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Integer)}, typeid(hodel::Grid)});
    neurons.emplace("upscale0", Neuron{"upscale", hodel::upscale, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Integer)}, typeid(hodel::Grid)});
    neurons.emplace("upscale1", Neuron{"upscale", hodel::upscale, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Integer)}, typeid(hodel::Object)});
    neurons.emplace("downscale", Neuron{"downscale", hodel::downscale, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Integer)}, typeid(hodel::Grid)});
    neurons.emplace("hconcat", Neuron{"hconcat", hodel::hconcat, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("vconcat", Neuron{"vconcat", hodel::vconcat, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("subgrid0", Neuron{"subgrid", hodel::subgrid, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("subgrid1", Neuron{"subgrid", hodel::subgrid, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("cellwise", Neuron{"cellwise", hodel::cellwise, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Grid), typeid(hodel::Integer)}, typeid(hodel::Grid)});
    neurons.emplace("replace", Neuron{"replace", hodel::replace, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Integer), typeid(hodel::Integer)}, typeid(hodel::Grid)});
    neurons.emplace("switch", Neuron{"switch", hodel::switch_, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::Integer), typeid(hodel::Integer)}, typeid(hodel::Grid)});
    neurons.emplace("center0", Neuron{"center", hodel::center, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("center1", Neuron{"center", hodel::center, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("position0", Neuron{"position", hodel::position, std::vector<std::type_index>{typeid(hodel::Indices), typeid(hodel::Indices)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("position1", Neuron{"position", hodel::position, std::vector<std::type_index>{typeid(hodel::Object), typeid(hodel::Object)}, typeid(hodel::IntegerTuple)});
    neurons.emplace("index", Neuron{"index", hodel::index, std::vector<std::type_index>{typeid(hodel::Grid), typeid(hodel::IntegerTuple)}, typeid(hodel::Integer)});
    neurons.emplace("canvas", Neuron{"canvas", hodel::canvas, std::vector<std::type_index>{typeid(hodel::Integer), typeid(hodel::IntegerTuple)}, typeid(hodel::Grid)});
    neurons.emplace("corners0", Neuron{"corners", hodel::corners, std::vector<std::type_index>{typeid(hodel::Indices)}, typeid(hodel::Indices)});
    neurons.emplace("corners1", Neuron{"corners", hodel::corners, std::vector<std::type_index>{typeid(hodel::Object)}, typeid(hodel::Indices)});
    neurons.emplace("trim", Neuron{"trim", hodel::trim, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("tophalf", Neuron{"tophalf", hodel::tophalf, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("bottomhalf", Neuron{"bottomhalf", hodel::bottomhalf, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("lefthalf", Neuron{"lefthalf", hodel::lefthalf, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});
    neurons.emplace("righthalf", Neuron{"righthalf", hodel::righthalf, std::vector<std::type_index>{typeid(hodel::Grid)}, typeid(hodel::Grid)});

    return neurons;
}
