#include "aicpp/DslSystem.h"
#include "aicpp/Hodel.h"

using namespace aicpp;

std::map<std::string, Neuron> aicpp::dslVariableNeurons()
{
    std::map<std::string, Neuron> neurons;

    neurons.emplace("F", Neuron{"F", [] (std::vector<std::any> const&) -> std::any { return hdl::F; }, std::vector<std::type_index>{}, typeid(hdl::Boolean)});
    neurons.emplace("T", Neuron{"T", [] (std::vector<std::any> const&) -> std::any { return hdl::T; }, std::vector<std::type_index>{}, typeid(hdl::Boolean)});
    neurons.emplace("ZERO", Neuron{"ZERO", [] (std::vector<std::any> const&) -> std::any { return hdl::ZERO; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("ONE", Neuron{"ONE", [] (std::vector<std::any> const&) -> std::any { return hdl::ONE; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("TWO", Neuron{"TWO", [] (std::vector<std::any> const&) -> std::any { return hdl::TWO; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("THREE", Neuron{"THREE", [] (std::vector<std::any> const&) -> std::any { return hdl::THREE; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("FOUR", Neuron{"FOUR", [] (std::vector<std::any> const&) -> std::any { return hdl::FOUR; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("FIVE", Neuron{"FIVE", [] (std::vector<std::any> const&) -> std::any { return hdl::FIVE; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("SIX", Neuron{"SIX", [] (std::vector<std::any> const&) -> std::any { return hdl::SIX; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("SEVEN", Neuron{"SEVEN", [] (std::vector<std::any> const&) -> std::any { return hdl::SEVEN; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("EIGHT", Neuron{"EIGHT", [] (std::vector<std::any> const&) -> std::any { return hdl::EIGHT; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("NINE", Neuron{"NINE", [] (std::vector<std::any> const&) -> std::any { return hdl::NINE; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("TEN", Neuron{"TEN", [] (std::vector<std::any> const&) -> std::any { return hdl::TEN; }, std::vector<std::type_index>{}, typeid(hdl::Integer)});
    neurons.emplace("U_ONE", Neuron{"U_ONE", [] (std::vector<std::any> const&) -> std::any { return hdl::U_ONE; }, std::vector<std::type_index>{}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("U_TWO", Neuron{"U_TWO", [] (std::vector<std::any> const&) -> std::any { return hdl::U_TWO; }, std::vector<std::type_index>{}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("U_THREE", Neuron{"U_THREE", [] (std::vector<std::any> const&) -> std::any { return hdl::U_THREE; }, std::vector<std::type_index>{}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("U_FOUR", Neuron{"U_FOUR", [] (std::vector<std::any> const&) -> std::any { return hdl::U_FOUR; }, std::vector<std::type_index>{}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("U_FIVE", Neuron{"U_FIVE", [] (std::vector<std::any> const&) -> std::any { return hdl::U_FIVE; }, std::vector<std::type_index>{}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("U_SIX", Neuron{"U_SIX", [] (std::vector<std::any> const&) -> std::any { return hdl::U_SIX; }, std::vector<std::type_index>{}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("U_SEVEN", Neuron{"U_SEVEN", [] (std::vector<std::any> const&) -> std::any { return hdl::U_SEVEN; }, std::vector<std::type_index>{}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("U_EIGHT", Neuron{"U_EIGHT", [] (std::vector<std::any> const&) -> std::any { return hdl::U_EIGHT; }, std::vector<std::type_index>{}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("U_NINE", Neuron{"U_NINE", [] (std::vector<std::any> const&) -> std::any { return hdl::U_NINE; }, std::vector<std::type_index>{}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("U_TEN", Neuron{"U_TEN", [] (std::vector<std::any> const&) -> std::any { return hdl::U_TEN; }, std::vector<std::type_index>{}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("DOWN", Neuron{"DOWN", [] (std::vector<std::any> const&) -> std::any { return hdl::DOWN; }, std::vector<std::type_index>{}, typeid(hdl::IntegerTuple)});
    neurons.emplace("RIGHT", Neuron{"RIGHT", [] (std::vector<std::any> const&) -> std::any { return hdl::RIGHT; }, std::vector<std::type_index>{}, typeid(hdl::IntegerTuple)});
    neurons.emplace("UP", Neuron{"UP", [] (std::vector<std::any> const&) -> std::any { return hdl::UP; }, std::vector<std::type_index>{}, typeid(hdl::IntegerTuple)});
    neurons.emplace("LEFT", Neuron{"LEFT", [] (std::vector<std::any> const&) -> std::any { return hdl::LEFT; }, std::vector<std::type_index>{}, typeid(hdl::IntegerTuple)});
    neurons.emplace("ORIGIN", Neuron{"ORIGIN", [] (std::vector<std::any> const&) -> std::any { return hdl::ORIGIN; }, std::vector<std::type_index>{}, typeid(hdl::IntegerTuple)});
    neurons.emplace("UNITY", Neuron{"UNITY", [] (std::vector<std::any> const&) -> std::any { return hdl::UNITY; }, std::vector<std::type_index>{}, typeid(hdl::IntegerTuple)});
    neurons.emplace("NEG_UNITY", Neuron{"NEG_UNITY", [] (std::vector<std::any> const&) -> std::any { return hdl::NEG_UNITY; }, std::vector<std::type_index>{}, typeid(hdl::IntegerTuple)});
    neurons.emplace("UP_RIGHT", Neuron{"UP_RIGHT", [] (std::vector<std::any> const&) -> std::any { return hdl::UP_RIGHT; }, std::vector<std::type_index>{}, typeid(hdl::IntegerTuple)});
    neurons.emplace("DOWN_LEFT", Neuron{"DOWN_LEFT", [] (std::vector<std::any> const&) -> std::any { return hdl::DOWN_LEFT; }, std::vector<std::type_index>{}, typeid(hdl::IntegerTuple)});
    neurons.emplace("ZERO_BY_TWO", Neuron{"ZERO_BY_TWO", [] (std::vector<std::any> const&) -> std::any { return hdl::ZERO_BY_TWO; }, std::vector<std::type_index>{}, typeid(hdl::Size)});
    neurons.emplace("TWO_BY_ZERO", Neuron{"TWO_BY_ZERO", [] (std::vector<std::any> const&) -> std::any { return hdl::TWO_BY_ZERO; }, std::vector<std::type_index>{}, typeid(hdl::Size)});
    neurons.emplace("TWO_BY_TWO", Neuron{"TWO_BY_TWO", [] (std::vector<std::any> const&) -> std::any { return hdl::TWO_BY_TWO; }, std::vector<std::type_index>{}, typeid(hdl::Size)});
    neurons.emplace("THREE_BY_THREE", Neuron{"THREE_BY_THREE", [] (std::vector<std::any> const&) -> std::any { return hdl::THREE_BY_THREE; }, std::vector<std::type_index>{}, typeid(hdl::Size)});

    return neurons;
}

std::map<std::string, Neuron> aicpp::dslPrimitiveNeurons()
{
    std::map<std::string, Neuron> neurons;

    neurons.emplace("identity0", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("identity1", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Object)});
    neurons.emplace("identity2", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("identity3", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::Patch)});
    neurons.emplace("identity4", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::Cell)}, typeid(hdl::Cell)});
    neurons.emplace("identity5", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("identity6", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Objects)});
    neurons.emplace("identity7", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("identity8", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::UnsignedInteger)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("identity9", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::Boolean)}, typeid(hdl::Boolean)});
    neurons.emplace("identity10", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("identity11", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::Size)}, typeid(hdl::Size)});
    neurons.emplace("identity12", Neuron{"identity", hdl::identity, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Indices)});
    neurons.emplace("add0", Neuron{"add", hdl::add, std::vector<std::type_index>{typeid(hdl::IntegerTuple), typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("add1", Neuron{"add", hdl::add, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("subtract0", Neuron{"subtract", hdl::subtract, std::vector<std::type_index>{typeid(hdl::IntegerTuple), typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("subtract1", Neuron{"subtract", hdl::subtract, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("multiply0", Neuron{"multiply", hdl::multiply, std::vector<std::type_index>{typeid(hdl::IntegerTuple), typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("multiply1", Neuron{"multiply", hdl::multiply, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("divide0", Neuron{"divide", hdl::divide, std::vector<std::type_index>{typeid(hdl::IntegerTuple), typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("divide1", Neuron{"divide", hdl::divide, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("invert0", Neuron{"invert", hdl::invert, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("invert1", Neuron{"invert", hdl::invert, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("even", Neuron{"even", hdl::even, std::vector<std::type_index>{typeid(hdl::Boolean)}, typeid(hdl::Integer)});
    neurons.emplace("double_", Neuron{"double_", hdl::double_, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("halve", Neuron{"halve", hdl::halve, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("flip", Neuron{"flip", hdl::flip, std::vector<std::type_index>{typeid(hdl::Boolean)}, typeid(hdl::Boolean)});
    neurons.emplace("equality0", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("equality1", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Object)});
    neurons.emplace("equality2", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("equality3", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::Patch)});
    neurons.emplace("equality4", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::Cell)}, typeid(hdl::Cell)});
    neurons.emplace("equality5", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("equality6", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Objects)});
    neurons.emplace("equality7", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("equality8", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::UnsignedInteger)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("equality9", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::Boolean)}, typeid(hdl::Boolean)});
    neurons.emplace("equality10", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("equality11", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::Size)}, typeid(hdl::Size)});
    neurons.emplace("equality12", Neuron{"equality", hdl::equality, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Indices)});
    neurons.emplace("contained0", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerTuple), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained1", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Cell), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained2", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerSet), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained3", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained4", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained5", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Size), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained6", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained7", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Patch), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained8", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Indices), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained9", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IndicesSet), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained10", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerTuple), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained11", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Boolean), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained12", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Cell), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained13", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Patch), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained14", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Objects), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained15", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained16", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained17", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IndicesSet), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained18", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerSet), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained19", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::UnsignedInteger), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained20", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained21", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Objects), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained22", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Objects), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained23", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Indices), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained24", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Boolean), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained25", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerTuple), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained26", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained27", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Cell), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained28", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained29", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Size), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained30", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Indices), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained31", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IndicesSet), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained32", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained33", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::UnsignedInteger), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained34", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained35", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerTuple), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained36", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Objects), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained37", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Cell), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained38", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained39", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Size), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained40", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Patch), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained41", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Patch), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained42", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IndicesSet), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained43", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Size), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained44", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Boolean), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained45", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained46", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerSet), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained47", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained48", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerSet), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained49", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Patch), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained50", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Objects), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained51", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::UnsignedInteger), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained52", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Boolean), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained53", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerTuple), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained54", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Cell), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained55", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Indices), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained56", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained57", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained58", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerSet), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained59", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::UnsignedInteger), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained60", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::UnsignedInteger), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained61", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IndicesSet), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained62", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained63", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Objects), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained64", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerTuple), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained65", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Cell), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained66", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Boolean), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained67", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained68", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained69", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Size), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained70", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Size), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained71", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Indices), typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained72", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Patch), typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("contained73", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IndicesSet), typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("contained74", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Boolean), typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("contained75", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::Indices), typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("contained76", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::IntegerSet), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("contained77", Neuron{"contained", hdl::contained, std::vector<std::type_index>{typeid(hdl::UnsignedInteger), typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("combine0", Neuron{"combine", hdl::combine, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::Object)}, typeid(hdl::Object)});
    neurons.emplace("combine1", Neuron{"combine", hdl::combine, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("combine2", Neuron{"combine", hdl::combine, std::vector<std::type_index>{typeid(hdl::Indices), typeid(hdl::Indices)}, typeid(hdl::Indices)});
    neurons.emplace("combine3", Neuron{"combine", hdl::combine, std::vector<std::type_index>{typeid(hdl::Objects), typeid(hdl::Objects)}, typeid(hdl::Objects)});
    neurons.emplace("combine4", Neuron{"combine", hdl::combine, std::vector<std::type_index>{typeid(hdl::IndicesSet), typeid(hdl::IndicesSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("combine5", Neuron{"combine", hdl::combine, std::vector<std::type_index>{typeid(hdl::IntegerSet), typeid(hdl::IntegerSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("intersection0", Neuron{"intersection", hdl::intersection, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::Object)}, typeid(hdl::Object)});
    neurons.emplace("intersection1", Neuron{"intersection", hdl::intersection, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("intersection2", Neuron{"intersection", hdl::intersection, std::vector<std::type_index>{typeid(hdl::Indices), typeid(hdl::Indices)}, typeid(hdl::Indices)});
    neurons.emplace("intersection3", Neuron{"intersection", hdl::intersection, std::vector<std::type_index>{typeid(hdl::Objects), typeid(hdl::Objects)}, typeid(hdl::Objects)});
    neurons.emplace("intersection4", Neuron{"intersection", hdl::intersection, std::vector<std::type_index>{typeid(hdl::IndicesSet), typeid(hdl::IndicesSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("intersection5", Neuron{"intersection", hdl::intersection, std::vector<std::type_index>{typeid(hdl::IntegerSet), typeid(hdl::IntegerSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("difference0", Neuron{"difference", hdl::difference, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::Object)}, typeid(hdl::Object)});
    neurons.emplace("difference1", Neuron{"difference", hdl::difference, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("difference2", Neuron{"difference", hdl::difference, std::vector<std::type_index>{typeid(hdl::Indices), typeid(hdl::Indices)}, typeid(hdl::Indices)});
    neurons.emplace("difference3", Neuron{"difference", hdl::difference, std::vector<std::type_index>{typeid(hdl::Objects), typeid(hdl::Objects)}, typeid(hdl::Objects)});
    neurons.emplace("difference4", Neuron{"difference", hdl::difference, std::vector<std::type_index>{typeid(hdl::IndicesSet), typeid(hdl::IndicesSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("difference5", Neuron{"difference", hdl::difference, std::vector<std::type_index>{typeid(hdl::IntegerSet), typeid(hdl::IntegerSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("greater", Neuron{"greater", hdl::greater, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::Integer)}, typeid(hdl::Boolean)});
    neurons.emplace("size0", Neuron{"size", hdl::size, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("size1", Neuron{"size", hdl::size, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("size2", Neuron{"size", hdl::size, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("size3", Neuron{"size", hdl::size, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("size4", Neuron{"size", hdl::size, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("size5", Neuron{"size", hdl::size, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("maximum", Neuron{"maximum", hdl::maximum, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Integer)});
    neurons.emplace("minimum", Neuron{"minimum", hdl::minimum, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Integer)});
    neurons.emplace("initset0", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Boolean)}, typeid(hdl::Grid)});
    neurons.emplace("initset1", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset2", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset3", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Boolean)}, typeid(hdl::Objects)});
    neurons.emplace("initset4", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Indices)});
    neurons.emplace("initset5", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset6", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::UnsignedInteger)}, typeid(hdl::Indices)});
    neurons.emplace("initset7", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Cell)}, typeid(hdl::Indices)});
    neurons.emplace("initset8", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Grid)});
    neurons.emplace("initset9", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Object)});
    neurons.emplace("initset10", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset11", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::UnsignedInteger)}, typeid(hdl::Grid)});
    neurons.emplace("initset12", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Cell)}, typeid(hdl::Grid)});
    neurons.emplace("initset13", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Objects)});
    neurons.emplace("initset14", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Indices)});
    neurons.emplace("initset15", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Indices)});
    neurons.emplace("initset16", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::UnsignedInteger)}, typeid(hdl::Objects)});
    neurons.emplace("initset17", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Cell)}, typeid(hdl::Objects)});
    neurons.emplace("initset18", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset19", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Object)});
    neurons.emplace("initset20", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("initset21", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset22", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Object)});
    neurons.emplace("initset23", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Objects)});
    neurons.emplace("initset24", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Objects)});
    neurons.emplace("initset25", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset26", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Indices)});
    neurons.emplace("initset27", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::Object)});
    neurons.emplace("initset28", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Size)}, typeid(hdl::Object)});
    neurons.emplace("initset29", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Grid)});
    neurons.emplace("initset30", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset31", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::Indices)});
    neurons.emplace("initset32", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset33", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Boolean)}, typeid(hdl::Object)});
    neurons.emplace("initset34", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Objects)});
    neurons.emplace("initset35", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset36", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::Grid)});
    neurons.emplace("initset37", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Grid)});
    neurons.emplace("initset38", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset39", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::Objects)});
    neurons.emplace("initset40", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset41", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Size)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset42", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Object)});
    neurons.emplace("initset43", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::UnsignedInteger)}, typeid(hdl::Object)});
    neurons.emplace("initset44", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Cell)}, typeid(hdl::Object)});
    neurons.emplace("initset45", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Indices)});
    neurons.emplace("initset46", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset47", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Boolean)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset48", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Grid)});
    neurons.emplace("initset49", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset50", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Size)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset51", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Object)});
    neurons.emplace("initset52", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Object)});
    neurons.emplace("initset53", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Indices)});
    neurons.emplace("initset54", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Objects)});
    neurons.emplace("initset55", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Indices)});
    neurons.emplace("initset56", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset57", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Grid)});
    neurons.emplace("initset58", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::UnsignedInteger)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset59", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Boolean)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset60", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Cell)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset61", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Objects)});
    neurons.emplace("initset62", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Grid)});
    neurons.emplace("initset63", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::Indices)});
    neurons.emplace("initset64", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Size)}, typeid(hdl::Indices)});
    neurons.emplace("initset65", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Object)});
    neurons.emplace("initset66", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Objects)});
    neurons.emplace("initset67", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset68", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("initset69", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::Grid)});
    neurons.emplace("initset70", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset71", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Size)}, typeid(hdl::Grid)});
    neurons.emplace("initset72", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::UnsignedInteger)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset73", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Cell)}, typeid(hdl::IndicesSet)});
    neurons.emplace("initset74", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Boolean)}, typeid(hdl::Indices)});
    neurons.emplace("initset75", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::Objects)});
    neurons.emplace("initset76", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::Object)});
    neurons.emplace("initset77", Neuron{"initset", hdl::initset, std::vector<std::type_index>{typeid(hdl::Size)}, typeid(hdl::Objects)});
    neurons.emplace("both", Neuron{"both", hdl::both, std::vector<std::type_index>{typeid(hdl::Boolean), typeid(hdl::Boolean)}, typeid(hdl::Boolean)});
    neurons.emplace("either", Neuron{"either", hdl::either, std::vector<std::type_index>{typeid(hdl::Boolean), typeid(hdl::Boolean)}, typeid(hdl::Boolean)});
    neurons.emplace("increment0", Neuron{"increment", hdl::increment, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("increment1", Neuron{"increment", hdl::increment, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("decrement0", Neuron{"decrement", hdl::decrement, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("decrement1", Neuron{"decrement", hdl::decrement, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("crement0", Neuron{"crement", hdl::crement, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("crement1", Neuron{"crement", hdl::crement, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("sign0", Neuron{"sign", hdl::sign, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("sign1", Neuron{"sign", hdl::sign, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Integer)});
    neurons.emplace("positive0", Neuron{"positive", hdl::positive, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::Boolean)});
    neurons.emplace("positive1", Neuron{"positive", hdl::positive, std::vector<std::type_index>{typeid(hdl::IntegerTuple)}, typeid(hdl::Boolean)});
    neurons.emplace("toivec", Neuron{"toivec", hdl::toivec, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("tojvec", Neuron{"tojvec", hdl::tojvec, std::vector<std::type_index>{typeid(hdl::Integer)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("first0", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Integer)});
    neurons.emplace("first1", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::IndicesSet)});
    neurons.emplace("first2", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("first3", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Indices)});
    neurons.emplace("first4", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::IntegerSet)});
    neurons.emplace("first5", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("first6", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Cell)});
    neurons.emplace("first7", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Grid)});
    neurons.emplace("first8", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Object)});
    neurons.emplace("first9", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Patch)});
    neurons.emplace("first10", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Integer)});
    neurons.emplace("first11", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Size)});
    neurons.emplace("first12", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Objects)});
    neurons.emplace("first13", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Indices)});
    neurons.emplace("first14", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Indices)});
    neurons.emplace("first15", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::IndicesSet)});
    neurons.emplace("first16", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("first17", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("first18", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("first19", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("first20", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("first21", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Object)});
    neurons.emplace("first22", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Objects)});
    neurons.emplace("first23", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Objects)});
    neurons.emplace("first24", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Integer)});
    neurons.emplace("first25", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::IntegerSet)});
    neurons.emplace("first26", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Size)});
    neurons.emplace("first27", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Indices)});
    neurons.emplace("first28", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("first29", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Cell)});
    neurons.emplace("first30", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("first31", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("first32", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Grid)});
    neurons.emplace("first33", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Patch)});
    neurons.emplace("first34", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::IndicesSet)});
    neurons.emplace("first35", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Objects)});
    neurons.emplace("first36", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("first37", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("first38", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Cell)});
    neurons.emplace("first39", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("first40", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Grid)});
    neurons.emplace("first41", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Cell)});
    neurons.emplace("first42", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("first43", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Patch)});
    neurons.emplace("first44", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Patch)});
    neurons.emplace("first45", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Object)});
    neurons.emplace("first46", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Indices)});
    neurons.emplace("first47", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("first48", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Integer)});
    neurons.emplace("first49", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Size)});
    neurons.emplace("first50", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("first51", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("first52", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Grid)});
    neurons.emplace("first53", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("first54", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Object)});
    neurons.emplace("first55", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Object)});
    neurons.emplace("first56", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Patch)});
    neurons.emplace("first57", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Objects)});
    neurons.emplace("first58", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Integer)});
    neurons.emplace("first59", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Size)});
    neurons.emplace("first60", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Size)});
    neurons.emplace("first61", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Indices)});
    neurons.emplace("first62", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::IntegerSet)});
    neurons.emplace("first63", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("first64", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("first65", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("first66", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Grid)});
    neurons.emplace("first67", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Object)});
    neurons.emplace("first68", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Objects)});
    neurons.emplace("first69", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::IntegerSet)});
    neurons.emplace("first70", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("first71", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("first72", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::IndicesSet)});
    neurons.emplace("first73", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Integer)});
    neurons.emplace("first74", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Size)});
    neurons.emplace("first75", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Cell)});
    neurons.emplace("first76", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Cell)});
    neurons.emplace("first77", Neuron{"first", hdl::first, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Patch)});
    neurons.emplace("last0", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Integer)});
    neurons.emplace("last1", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::IndicesSet)});
    neurons.emplace("last2", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("last3", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Indices)});
    neurons.emplace("last4", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::IntegerSet)});
    neurons.emplace("last5", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("last6", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Cell)});
    neurons.emplace("last7", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Grid)});
    neurons.emplace("last8", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Object)});
    neurons.emplace("last9", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Patch)});
    neurons.emplace("last10", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Integer)});
    neurons.emplace("last11", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Size)});
    neurons.emplace("last12", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Objects)});
    neurons.emplace("last13", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Indices)});
    neurons.emplace("last14", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Indices)});
    neurons.emplace("last15", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::IndicesSet)});
    neurons.emplace("last16", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Boolean)});
    neurons.emplace("last17", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("last18", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("last19", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("last20", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("last21", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Object)});
    neurons.emplace("last22", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Objects)});
    neurons.emplace("last23", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Objects)});
    neurons.emplace("last24", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Integer)});
    neurons.emplace("last25", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::IntegerSet)});
    neurons.emplace("last26", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Size)});
    neurons.emplace("last27", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Indices)});
    neurons.emplace("last28", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Boolean)});
    neurons.emplace("last29", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Cell)});
    neurons.emplace("last30", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("last31", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Boolean)});
    neurons.emplace("last32", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Grid)});
    neurons.emplace("last33", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Patch)});
    neurons.emplace("last34", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::IndicesSet)});
    neurons.emplace("last35", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Objects)});
    neurons.emplace("last36", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("last37", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("last38", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Cell)});
    neurons.emplace("last39", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Boolean)});
    neurons.emplace("last40", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Grid)});
    neurons.emplace("last41", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Cell)});
    neurons.emplace("last42", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("last43", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Patch)});
    neurons.emplace("last44", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Patch)});
    neurons.emplace("last45", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Object)});
    neurons.emplace("last46", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Indices)});
    neurons.emplace("last47", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::IndicesSet)});
    neurons.emplace("last48", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Integer)});
    neurons.emplace("last49", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Size)});
    neurons.emplace("last50", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("last51", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("last52", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Grid)});
    neurons.emplace("last53", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Boolean)});
    neurons.emplace("last54", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Object)});
    neurons.emplace("last55", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Object)});
    neurons.emplace("last56", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Patch)});
    neurons.emplace("last57", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Objects)});
    neurons.emplace("last58", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Integer)});
    neurons.emplace("last59", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Size)});
    neurons.emplace("last60", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Size)});
    neurons.emplace("last61", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Indices)});
    neurons.emplace("last62", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::IntegerSet)});
    neurons.emplace("last63", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Boolean)});
    neurons.emplace("last64", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("last65", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("last66", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Grid)});
    neurons.emplace("last67", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Object)});
    neurons.emplace("last68", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IntegerSet)}, typeid(hdl::Objects)});
    neurons.emplace("last69", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::IntegerSet)});
    neurons.emplace("last70", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::IntegerSet)});
    neurons.emplace("last71", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::UnsignedInteger)});
    neurons.emplace("last72", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::IndicesSet)});
    neurons.emplace("last73", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Integer)});
    neurons.emplace("last74", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Objects)}, typeid(hdl::Size)});
    neurons.emplace("last75", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Cell)});
    neurons.emplace("last76", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::IndicesSet)}, typeid(hdl::Cell)});
    neurons.emplace("last77", Neuron{"last", hdl::last, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Patch)});
    neurons.emplace("astuple", Neuron{"astuple", hdl::astuple, std::vector<std::type_index>{typeid(hdl::Integer), typeid(hdl::Integer)}, typeid(hdl::IntegerTuple)});
    neurons.emplace("crop", Neuron{"crop", hdl::crop, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::IntegerTuple), typeid(hdl::Size)}, typeid(hdl::Grid)});
    neurons.emplace("toindices0", Neuron{"toindices", hdl::toindices, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Indices)});
    neurons.emplace("toindices1", Neuron{"toindices", hdl::toindices, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Indices)});
    neurons.emplace("shift0", Neuron{"shift", hdl::shift, std::vector<std::type_index>{typeid(hdl::Indices), typeid(hdl::IntegerTuple)}, typeid(hdl::Indices)});
    neurons.emplace("shift1", Neuron{"shift", hdl::shift, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::IntegerTuple)}, typeid(hdl::Object)});
    neurons.emplace("uppermost0", Neuron{"uppermost", hdl::uppermost, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Integer)});
    neurons.emplace("uppermost1", Neuron{"uppermost", hdl::uppermost, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Integer)});
    neurons.emplace("lowermost0", Neuron{"lowermost", hdl::lowermost, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Integer)});
    neurons.emplace("lowermost1", Neuron{"lowermost", hdl::lowermost, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Integer)});
    neurons.emplace("leftmost0", Neuron{"leftmost", hdl::leftmost, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Integer)});
    neurons.emplace("leftmost1", Neuron{"leftmost", hdl::leftmost, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Integer)});
    neurons.emplace("rightmost0", Neuron{"rightmost", hdl::rightmost, std::vector<std::type_index>{typeid(hdl::Indices)}, typeid(hdl::Integer)});
    neurons.emplace("rightmost1", Neuron{"rightmost", hdl::rightmost, std::vector<std::type_index>{typeid(hdl::Object)}, typeid(hdl::Integer)});
    neurons.emplace("rot90", Neuron{"rot90", hdl::rot90, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("rot180", Neuron{"rot180", hdl::rot180, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("rot270", Neuron{"rot270", hdl::rot270, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("hmirror0", Neuron{"hmirror", hdl::hmirror, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("hmirror1", Neuron{"hmirror", hdl::hmirror, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::Patch)});
    neurons.emplace("vmirror0", Neuron{"vmirror", hdl::vmirror, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("vmirror1", Neuron{"vmirror", hdl::vmirror, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::Patch)});
    neurons.emplace("dmirror0", Neuron{"dmirror", hdl::dmirror, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("dmirror1", Neuron{"dmirror", hdl::dmirror, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::Patch)});
    neurons.emplace("cmirror0", Neuron{"cmirror", hdl::cmirror, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("cmirror1", Neuron{"cmirror", hdl::cmirror, std::vector<std::type_index>{typeid(hdl::Patch)}, typeid(hdl::Patch)});
    neurons.emplace("hupscale", Neuron{"hupscale", hdl::hupscale, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::UnsignedInteger)}, typeid(hdl::Grid)});
    neurons.emplace("vupscale", Neuron{"vupscale", hdl::vupscale, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::UnsignedInteger)}, typeid(hdl::Grid)});
    neurons.emplace("upscale0", Neuron{"upscale", hdl::upscale, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::UnsignedInteger)}, typeid(hdl::Grid)});
    neurons.emplace("upscale1", Neuron{"upscale", hdl::upscale, std::vector<std::type_index>{typeid(hdl::Object), typeid(hdl::UnsignedInteger)}, typeid(hdl::Object)});
    neurons.emplace("downscale", Neuron{"downscale", hdl::downscale, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::UnsignedInteger)}, typeid(hdl::Grid)});
    neurons.emplace("hconcat", Neuron{"hconcat", hdl::hconcat, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("vconcat", Neuron{"vconcat", hdl::vconcat, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("replace", Neuron{"replace", hdl::replace, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Integer), typeid(hdl::Integer)}, typeid(hdl::Grid)});
    neurons.emplace("switch_", Neuron{"switch_", hdl::switch_, std::vector<std::type_index>{typeid(hdl::Grid), typeid(hdl::Integer), typeid(hdl::Integer)}, typeid(hdl::Grid)});
    neurons.emplace("tophalf", Neuron{"tophalf", hdl::tophalf, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("bottomhalf", Neuron{"bottomhalf", hdl::bottomhalf, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("lefthalf", Neuron{"lefthalf", hdl::lefthalf, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});
    neurons.emplace("righthalf", Neuron{"righthalf", hdl::righthalf, std::vector<std::type_index>{typeid(hdl::Grid)}, typeid(hdl::Grid)});

    return neurons;
}
