name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker
        run: git clone https://github.com/arcprize/ARC-AGI-2.git && docker build -t aicpp .
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Run tests
        run: docker run aicpp && cd scripts && python -m pytest -sxv engine.py && git clone https://github.com/michaelhodel/arc-dsl.git && mkdir proposals && python -m pytest -sxv test_arc.py
